import { IPrizeConfig, IPersonConfig } from '@/types/storeType';

export const defaultPersonList = <IPersonConfig[]>
  [
    {
      "uid": "1",
      "name": "Lưu Văn Tuyển",
      "department": "Ủy viên HĐQT - Phó TGĐ Tập đoàn XDVN",
      "id": 0,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "2",
      "name": "Trần Tuấn Linh",
      "department": "Ủy viên HĐQT Tập đoàn XDVN",
      "id": 1,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "3",
      "name": "Phạm Thị Dung",
      "department": "Trưởng Ban Quản trị rủi ro - HĐQT Tập đoàn XDVN",
      "id": 2,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "4",
      "name": "Trần Đức Trung ",
      "department": "Chánh Văn phòng Đảng ủy Tập đoàn XDVN",
      "id": 3,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "5",
      "name": "Bùi Duy Anh",
      "department": "Phó Chánh Văn phòng Đảng ủy Tập đoàn XDVN",
      "id": 4,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "6",
      "name": "Đỗ Hữu Tạo",
      "department": "Chủ tịch HĐQT Tổng Công ty Hóa dầu Petrolimex",
      "id": 5,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "7",
      "name": "Lê Quang Tuấn",
      "department": "Tổng Giám đốc Tổng Công ty Hóa dầu Petrolimex",
      "id": 6,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "8",
      "name": "Phạm Thanh Hải",
      "department": "Chủ tịch HĐQT Tổng Công ty CP Bảo hiểm Petrolimex",
      "id": 7,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "9",
      "name": "Nguyễn Thị Hương Giang",
      "department": "Tổng Giám đốc Tổng Công ty CP Bảo hiểm Petrolimex",
      "id": 8,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "10",
      "name": "Nguyễn Quang Định",
      "department": "Chủ tịch HĐQT Tổng Công ty Gas Petrolimex",
      "id": 9,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "11",
      "name": "Phạm Quang Hưng",
      "department": "Tổng Giám đốc Tổng Công ty Dịch vụ xăng dầu Petrolimex",
      "id": 10,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "12",
      "name": "Lê Thị Thanh Hà",
      "department": "Chủ tịch kiêm Giám đốc Công ty Xăng dầu Khu vực III",
      "id": 11,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "13",
      "name": "Vũ Đình Hùng",
      "department": "Giám đốc Tổng kho Xăng dầu Thượng Lý",
      "id": 12,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "14",
      "name": "Vũ Thị Thanh Hương",
      "department": "Chánh Văn phòng Công ty Xăng dầu Khu vực III",
      "id": 13,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "15",
      "name": "Bùi Văn Thành",
      "department": "Chủ tịch Công ty Petajico Hà Nội",
      "id": 14,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "16",
      "name": "Phạm Quốc Hùng",
      "department": "Giám đốc Công ty Petajico Hà Nội",
      "id": 15,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "17",
      "name": "Hoàng Công Thành",
      "department": "Chủ tịch Công ty PTS Nghệ Tĩnh",
      "id": 16,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "18",
      "name": "Mạnh Xuân Hùng",
      "department": "Giám đốc Công ty PTS Nghệ Tĩnh",
      "id": 17,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "19",
      "name": "Đỗ Đông Đức",
      "department": "Tổng Giám đốc Petrolimex Singapore",
      "id": 18,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "20",
      "name": "Nguyễn Quang Hào",
      "department": "Chủ tịch HĐTV Công ty TNHH LD Kho ngoại quan XD Vân Phong",
      "id": 19,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "21",
      "name": "Trịnh Quốc Tuấn",
      "department": "Chánh Văn phòng Cục Hàng không Việt Nam",
      "id": 20,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "22",
      "name": "Trịnh Quang Khanh",
      "department": "Tổng Thư ký Hiệp hội XDVN",
      "id": 21,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "23",
      "name": "Bùi Doãn Nề",
      "department": "Phó Chủ tịch Hiệp hội Doanh nghiệp HKVN",
      "id": 22,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "24",
      "name": "Cao Tuấn Anh Dũng",
      "department": "Chủ tịch DHT Aviation",
      "id": 23,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "25",
      "name": "Lê Ngọc Thái",
      "department": "Giám đốc Vietcombank CN Hà Nội",
      "id": 24,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "26",
      "name": "Ngô Thị Minh Giang",
      "department": "Phó TP phụ trách Phòng KHDN1 Vietcombank CN Hà Nội",
      "id": 25,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "27",
      "name": "Đặng Quang Vinh",
      "department": "Giám đốc BIDV CN Hai Bà Trưng",
      "id": 26,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "28",
      "name": "Nhữ Việt Dũng",
      "department": "Trưởng phòng KHDN1 BIDV CN Hai Bà Trưng",
      "id": 27,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "29",
      "name": "Nguyễn Ngọc Linh",
      "department": "Giám đốc MBBank CN Hai Bà Trưng",
      "id": 28,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "30",
      "name": "Hồ Công Thành",
      "department": "Trưởng phòng KHDN lớn MBBank CN Hai Bà Trưng",
      "id": 29,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "31",
      "name": "Trần Thị Phương",
      "department": "Giám đốc khu vực kiêm Giám đốc Eximbank CN Hà Nội",
      "id": 30,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "32",
      "name": "Tạ Quang An",
      "department": "Phó Giám đốc Eximbank CN Hà Nội",
      "id": 31,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "33",
      "name": "Nguyễn Hoài Nam",
      "department": "Trưởng phòng Dịch vụ Công ty QL&DV Mipec",
      "id": 32,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "34",
      "name": "Phạm Thái Lai",
      "department": "Giám đốc Trung tâm Thông tin Kinh tế VCCI",
      "id": 33,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "35",
      "name": "Nguyễn Mạnh Hùng",
      "department": "Cán bộ phòng 3 - A04",
      "id": 34,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "36",
      "name": "Phạm Huy Thông",
      "department": "Chủ tịch HĐQT Công ty",
      "id": 35,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "37",
      "name": "Nguyễn Văn Học",
      "department": "Bí thư Đảng ủy, Ủy viên HĐQT, Tổng Giám đốc Công ty",
      "id": 36,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "38",
      "name": "Trần Thanh Long",
      "department": "Ủy viên HĐQT, Phó Tổng Giám đốc Công ty",
      "id": 37,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "39",
      "name": "Lê Minh Quốc",
      "department": "Phó TGĐ Công ty CP Hóa dầu Quân đội, Ủy viên HĐQT Công ty",
      "id": 38,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "40",
      "name": "Nguyễn Diệu Linh",
      "department": "Trưởng Ban Kiểm soát Công ty",
      "id": 39,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "41",
      "name": "Trần Thị Lan Phương",
      "department": "Thành viên Ban Kiểm soát Công ty",
      "id": 40,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "42",
      "name": "Nguyễn Anh Tú",
      "department": "Thành viên Ban Kiểm soát Công ty",
      "id": 41,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "43",
      "name": "Ngô Quốc Tuấn",
      "department": "Phó Tổng Giám đốc Công ty",
      "id": 42,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "44",
      "name": "Lương Hồ Anh",
      "department": "Phó Tổng Giám đốc Công ty",
      "id": 43,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "45",
      "name": "Nguyễn Mai Nam",
      "department": "Phó Tổng Giám đốc Công ty kiêm Giám đốc Chi nhánh tại Nội Bài",
      "id": 44,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "46",
      "name": "Nguyễn Văn Trung",
      "department": "Kế toán trưởng Công ty",
      "id": 45,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "47",
      "name": "Nguyễn Hồng Hải",
      "department": "Quyền Trưởng Ban Tổng hợp HĐQT Công ty",
      "id": 46,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "48",
      "name": "Ma Văn Tuyên",
      "department": "Trưởng phòng Nhân sự Công ty",
      "id": 47,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "49",
      "name": "Lê Vĩnh Hải",
      "department": "Chánh Văn phòng Công ty",
      "id": 48,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "50",
      "name": "Võ Văn Hùng",
      "department": "Trưởng phòng Kỹ thuật Công ty",
      "id": 49,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "51",
      "name": "Nguyễn Minh Đại",
      "department": "Phó Trưởng phòng phụ trách Phòng Kinh doanh Công ty",
      "id": 50,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "52",
      "name": "Nguyễn Nguyên Lục",
      "department": "Trưởng phòng ANAT Công ty",
      "id": 51,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "53",
      "name": "Trần Minh Thắng",
      "department": "Trưởng phòng CNTT Công ty",
      "id": 52,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "54",
      "name": "Hoàng Ngọc Dũng",
      "department": "Trưởng phòng ĐTXD Công ty",
      "id": 53,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "55",
      "name": "Nguyễn Hữu Thắng",
      "department": "Giám đốc Chi nhánh tại Phú Quốc",
      "id": 54,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "56",
      "name": "Đặng Hồng Toan",
      "department": "Giám đốc Chi nhánh tại TP HCM",
      "id": 55,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "57",
      "name": "Vũ Văn Dân",
      "department": "Giám đốc Chi nhánh tại Cam Ranh",
      "id": 56,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "58",
      "name": "Lê Văn Quý",
      "department": "Giám đốc Chi nhánh tại Cát Bi",
      "id": 57,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "59",
      "name": "Phan Trung Sơn",
      "department": "Giám đốc Chi nhánh tại Liên Khương",
      "id": 58,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "60",
      "name": "Lưu Anh Tuấn",
      "department": "Giám đốc Chi nhánh tại Đà Nẵng",
      "id": 59,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "61",
      "name": "Lê Xuân Sơn",
      "department": "Phó Chánh Văn phòng Công ty",
      "id": 60,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "62",
      "name": "Nguyễn Hữu Quý",
      "department": "Phó Trưởng phòng Nhân sự Công ty",
      "id": 61,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "63",
      "name": "Nguyễn Anh Quý",
      "department": "Trưởng phòng KT-TH Chi nhánh tại Cát Bi",
      "id": 62,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "64",
      "name": "Hồ Quốc Tuấn",
      "department": "Phó Giám đốc Chi nhánh tại Cam Ranh",
      "id": 63,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "65",
      "name": "Vũ Bảo Huy",
      "department": "Phó Giám đốc Chi nhánh tại Nội Bài",
      "id": 64,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "66",
      "name": "Lê Tự Minh",
      "department": "Trưởng phòng Hàng hóa Chi nhánh tại Đà Nẵng",
      "id": 65,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "67",
      "name": "Nguyễn Danh Tám",
      "department": "Trưởng phòng KT-TH Chi nhánh tại TPHCM",
      "id": 66,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "68",
      "name": "Nguyễn Nam Trà",
      "department": "Trưởng phòng KT-TH Chi nhánh tại Liên Khương",
      "id": 67,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "69",
      "name": "Đào Duy Khánh",
      "department": "Phó Giám đốc kiêm Trưởng phòng KT-TH Chi nhánh tại Phú Quốc",
      "id": 68,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "70",
      "name": "Nguyễn Văn Quảng",
      "department": "Phó Trưởng phòng TCKT Công ty",
      "id": 69,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "71",
      "name": "Hoàng Hải Hòa",
      "department": "Phó Giám đốc Chi nhánh tại Nội Bài",
      "id": 70,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "72",
      "name": "Trần Văn Sỹ",
      "department": "Trưởng phòng KT-TH Chi nhánh tại Cam Ranh",
      "id": 71,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "73",
      "name": "Trần Viết Trung",
      "department": "Phó Trưởng phòng ĐTXD Công ty",
      "id": 72,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "74",
      "name": "Nguyễn Ngọc Tú",
      "department": "PTP Kinh doanh",
      "id": 73,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "75",
      "name": "Phạm Hải Phong",
      "department": "CV Phòng Kinh doanh",
      "id": 74,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "76",
      "name": "Nguyễn Hoàng Quân",
      "department": "PTP Kỹ thuật",
      "id": 75,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "77",
      "name": "Lê Tự Duy",
      "department": "CV Phòng Kỹ thuật",
      "id": 76,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "78",
      "name": "Đoàn Duy An",
      "department": "Phòng Nhân sự",
      "id": 77,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "79",
      "name": "Trần Hoàng Anh",
      "department": "CV Phòng TCKT",
      "id": 78,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "80",
      "name": "Nguyễn Tuấn Anh",
      "department": "CV Phòng ANAT",
      "id": 79,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "81",
      "name": "Lưu Thị Thùy Trang",
      "department": "CV Phòng ANAT",
      "id": 80,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "82",
      "name": "Bùi Đức Mạnh",
      "department": "Phó Chánh Văn phòng",
      "id": 81,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "83",
      "name": "Trần Ánh Hồng",
      "department": "CV Văn phòng",
      "id": 82,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "84",
      "name": "Bùi Tuấn Anh",
      "department": "CV Văn phòng",
      "id": 83,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "85",
      "name": "Nguyễn Văn Khoa",
      "department": "Phòng ĐTXD",
      "id": 84,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "86",
      "name": "Nguyễn Văn Duy",
      "department": "Phòng CNTT",
      "id": 85,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "87",
      "name": "Đỗ Thị Hồ Thu",
      "department": "CV Ban Tổng hợp HĐQT",
      "id": 86,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "88",
      "name": "Trần Quốc Hải",
      "department": "Chi nhánh tại Nội Bài",
      "id": 87,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "89",
      "name": "Mai Anh Quý",
      "department": "Chi nhánh tại Nội Bài",
      "id": 88,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "90",
      "name": "Phạm Sơn Tùng",
      "department": "Chi nhánh tại Nội Bài",
      "id": 89,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "91",
      "name": "Phan Hữu Trung",
      "department": "Chi nhánh tại Nội Bài",
      "id": 90,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "92",
      "name": "Nguyễn Trác Hải",
      "department": "Chi nhánh tại Nội Bài",
      "id": 91,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "93",
      "name": "Phạm Văn Dung",
      "department": "Chi nhánh tại Nội Bài",
      "id": 92,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "94",
      "name": "Nguyễn Anh Tuấn",
      "department": "Chi nhánh tại Nội Bài",
      "id": 93,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "95",
      "name": "Lê Minh Thuận",
      "department": "Chi nhánh tại Nội Bài",
      "id": 94,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "96",
      "name": "Lò Văn Lương",
      "department": "Chi nhánh tại Nội Bài",
      "id": 95,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "97",
      "name": "Nguyễn Hoàng Long",
      "department": "Chi nhánh tại Nội Bài",
      "id": 96,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "98",
      "name": "Mai Văn Nam",
      "department": "Chi nhánh tại Nội Bài",
      "id": 97,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "99",
      "name": "Nguyễn Quang Đức",
      "department": "Chi nhánh tại Nội Bài",
      "id": 98,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "100",
      "name": "Phạm Thuỳ Trang",
      "department": "Chi nhánh tại Nội Bài",
      "id": 99,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "101",
      "name": "Nguyễn Thị Thu Thuỷ",
      "department": "Chi nhánh tại Nội Bài",
      "id": 100,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "102",
      "name": "Phạm Thanh Tùng",
      "department": "Chi nhánh tại Nội Bài",
      "id": 101,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "103",
      "name": "Lê Quang Hoà",
      "department": "Chi nhánh tại Nội Bài",
      "id": 102,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "104",
      "name": "Lê Đình Duy",
      "department": "Chi nhánh tại TPHCM",
      "id": 103,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "105",
      "name": "Hồ Nghĩa Quyết",
      "department": "Chi nhánh tại TPHCM",
      "id": 104,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "106",
      "name": "Vũ Hải Tuyến",
      "department": "Chi nhánh tại TPHCM",
      "id": 105,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "107",
      "name": "Võ Anh Tuấn ",
      "department": "Chi nhánh tại TPHCM",
      "id": 106,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "108",
      "name": "Đặng Duy Hải",
      "department": "Chi nhánh tại TPHCM",
      "id": 107,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "109",
      "name": "Phan Đình Công",
      "department": "Chi nhánh tại TPHCM",
      "id": 108,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "110",
      "name": "Trần Văn Hổ",
      "department": "Chi nhánh tại TPHCM",
      "id": 109,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "111",
      "name": "Mai Hữu Hậu",
      "department": "Chi nhánh tại TPHCM",
      "id": 110,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "112",
      "name": "Lê Thanh Bình",
      "department": "Chi nhánh tại TPHCM",
      "id": 111,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "113",
      "name": "Nguyễn Hoàng Minh Trí ",
      "department": "Chi nhánh tại TPHCM",
      "id": 112,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "114",
      "name": "Phạm Thị Mai Chi ",
      "department": "Chi nhánh tại TPHCM",
      "id": 113,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "115",
      "name": "Phạm Trường Giang",
      "department": "Chi nhánh tại TPHCM",
      "id": 114,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "116",
      "name": "Nguyễn Khắc Tuấn",
      "department": "Chi nhánh tại TPHCM",
      "id": 115,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "117",
      "name": "Lê Thị Lệ Xuân",
      "department": "Chi nhánh tại TPHCM",
      "id": 116,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "118",
      "name": "Trần Đình Bửu",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 117,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "119",
      "name": "Phạm Ngọc Thu",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 118,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "120",
      "name": "Trần Thiện Thanh",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 119,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "121",
      "name": "Phạm Thị Thu Hiền",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 120,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "122",
      "name": "Lê Thị Ngọc Thảo",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 121,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "123",
      "name": "Nguyễn Văn Giáp",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 122,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "124",
      "name": "Lê Nam Phú",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 123,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "125",
      "name": "Lê Xuân Văn",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 124,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "126",
      "name": "Nguyễn Hoàng Trâm Anh",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 125,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "127",
      "name": "Lê Minh Chính",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 126,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "128",
      "name": "Võ Nhứt",
      "department": "Chi nhánh tại Đà Nẵng",
      "id": 127,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "129",
      "name": "Tạ Quang Sơn",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 128,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "130",
      "name": "Lê Văn Nam",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 129,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "131",
      "name": "Trần Lê Văn",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 130,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "132",
      "name": "Hoàng Khánh Hòa",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 131,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "133",
      "name": "Đoàn Vũ Khánh Duy",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 132,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "134",
      "name": "Nguyễn Trường Thứ",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 133,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "135",
      "name": "Trần Đức Lợi",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 134,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "136",
      "name": "Phanh Thanh Chức",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 135,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "137",
      "name": "Phan Kiều Ngân",
      "department": "Chi nhánh tại Cam Ranh",
      "id": 136,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "138",
      "name": "Lưu Tuấn Anh",
      "department": "Chi nhánh tại Cát Bi",
      "id": 137,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "139",
      "name": "Lê Hải Nam",
      "department": "Chi nhánh tại Cát Bi",
      "id": 138,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "140",
      "name": "Nguyễn Quang Đức",
      "department": "Chi nhánh tại Cát Bi",
      "id": 139,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "141",
      "name": "Bùi Ngọc Minh",
      "department": "Chi nhánh tại Cát Bi",
      "id": 140,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "142",
      "name": "Vũ Đức Việt",
      "department": "Chi nhánh tại Cát Bi",
      "id": 141,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "143",
      "name": "Phạm Văn Hà",
      "department": "Chi nhánh tại Cát Bi",
      "id": 142,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "144",
      "name": "Trần Văn Tiến",
      "department": "Chi nhánh tại Cát Bi",
      "id": 143,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "145",
      "name": "Trịnh Quốc Anh",
      "department": "Chi nhánh tại Liên Khương",
      "id": 144,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "146",
      "name": "Bùi Mạnh Hiệp",
      "department": "Chi nhánh tại Liên Khương",
      "id": 145,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "147",
      "name": "Huỳnh Lâm Đức Nghĩa",
      "department": "Chi nhánh tại Liên Khương",
      "id": 146,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "148",
      "name": "Lê Ngọc Thái",
      "department": "Chi nhánh tại Phú Quốc",
      "id": 147,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "uid": "149",
      "name": "Đào Mạnh Linh",
      "department": "Chi nhánh tại Phú Quốc",
      "id": 148,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false,
      "x": 0,
      "y": 5,
      "identity": ""
    },
    {
      "id": 149,
      "uid": "150",
      "name": "Nguyễn Thanh Nhật",
      "department": "Chi nhánh tại Phú Quốc",
      "identity": "",
      "isWin": false,
      "createTime": "2024-12-31 18:28:39",
      "updateTime": "2024-12-31 18:28:39",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "x": 0,
      "y": 5
    }
  ]

export const defaultMusicList = [
  {
    id: 'Geoff Knorr - China (The Industrial Era).ogg' + new Date().getTime().toString(),
    name: 'Geoff Knorr - China (The Industrial Era).ogg',
    url: 'https://1kw20.fun/resource/audio/Geoff Knorr - China (The Industrial Era).ogg'
  },
  {
    id: 'xsmb' + new Date().getTime().toString(),
    name: 'XSMB music',
    url: 'xsmb.mp3'
  },

]

export const defaultPrizeList = <IPrizeConfig[]>[
  {
    id: '001',
    name: 'Giải ba',
    sort: 1,
    isAll: false,
    count: 20,
    isUsedCount: 0,
    picture: {
      id: '2',
      name: 'image_3',
      url: 'https://1kw20.fun/resource/image/image3.png'
    },
    separateCount: {
      enable: true,
      countList: []
    },
    desc: 'Giải ba',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '002',
    name: 'Giải nhì',
    sort: 2,
    isAll: false,
    count: 3,
    isUsedCount: 0,
    picture: {
      id: '1',
      name: 'image_2',
      url: 'https://1kw20.fun/resource/image/image2.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải nhì',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '003',
    name: 'Giải nhất',
    sort: 1,
    isAll: false,
    count: 1,
    isUsedCount: 0,
    picture: {
      id: '0',
      name: 'image_1',
      url: 'https://1kw20.fun/resource/image/image1.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải nhất',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  // {
  //   id: '004',
  //   name: 'Giải đặc biệt',
  //   sort: 4,
  //   isAll: false,
  //   count: 1,
  //   isUsedCount: 0,
  //   picture: {
  //     id: '3',
  //     name: 'image_4',
  //     url: 'https://1kw20.fun/resource/image/image4.png'
  //   },
  //   separateCount: {
  //     enable: false,
  //     countList: []
  //   },
  //   desc: 'Giải đặc biệt',
  //   isShow: true,
  //   isUsed: false,
  //   frequency: 1,
  // }
]
export const defaultCurrentPrize = <IPrizeConfig>{
  id: '001',
  name: 'Giải ba',
  sort: 1,
  isAll: false,
  count: 12,
  isUsedCount: 0,
  picture: {
    id: '2',
    name: 'image_3',
    url: 'https://1kw20.fun/resource/image/image3.png'
  },
  separateCount: {
    enable: true,
    countList: []
  },
  desc: 'Giải ba',
  isShow: true,
  isUsed: false,
  frequency: 1,
}
export const defaultTemporaryPrize = <IPrizeConfig>{
  id: '',
  name: '',
  sort: 0,
  isAll: false,
  count: 1,
  isUsedCount: 0,
  picture: {
    id: '-1',
    name: '',
    url: ''
  },
  separateCount: {
    enable: true,
    countList: []
  },
  desc: '',
  isShow: false,
  isUsed: false,
  frequency: 1,
}

export const defaultImageList = [
  {
    id: '0',
    name: 'background',
    url: 'bg-1.jpg'
  },
  // {
  //     id: '1',
  //     name: 'image_2',
  //     url: 'https://1kw20.fun/resource/image/image2.png'
  // },
  // {
  //     id: '2',
  //     name: 'image_3',
  //     url: 'https://1kw20.fun/resource/image/image3.png'
  // },
  // {
  //     id: '3',
  //     name: 'image_4',
  //     url: 'https://1kw20.fun/resource/image/image4.png'
  // },
  // {
  //     id: '4',
  //     name: 'image_5',
  //     url: 'https://1kw20.fun/resource/image/image5.png'
  // }
]
export const defaultPatternList = [21, 38, 55, 54, 53, 70, 87, 88, 89, 23, 40, 57, 74, 91, 92, 93, 76, 59, 42, 25, 24, 27, 28, 29, 46, 63, 62, 61, 78, 95, 96, 97, 20, 19, 31, 48, 65, 66, 67, 84, 101, 100, 99, 32, 33]
