import { IPrizeConfig, IPersonConfig } from '@/types/storeType';

export const defaultPersonList = <IPersonConfig[]>
  [
    {
      "uid": "1",
      "name": "Ông Phạm Thanh Hải",
      "identity": "Chủ tịch Hội Đồng Quản Trị",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 0,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "2",
      "name": "Bà Lê Thị Lan Anh",
      "identity": "Ủy viên Hội Đồng Quản Trị",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 1,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "3",
      "name": "Bà Trần Thị Bảo Ngọc",
      "identity": "Ủy viên Hội Đồng Quản Trị",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 2,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "4",
      "name": "Bà Trương Diệu Linh",
      "identity": "Ủy viên Hội Đồng Quản Trị",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 3,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "5",
      "name": "Bà Hà Kim Anh",
      "identity": "Ủy viên Hội Đồng Quản Trị",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 4,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "6",
      "name": "Bà Nguyễn Thị Hương Giang",
      "identity": "Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 5,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "7",
      "name": "Ông Bùi Hoài Giang",
      "identity": "Phó Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 6,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "8",
      "name": "Ông Lê Thanh Đạt",
      "identity": "Phó Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng hợp Hội Đồng Quản Trị",
      "id": 7,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "9",
      "name": "Ông Trần Anh Tuấn",
      "identity": "Phó Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng hợp Hội Đồng Quản Trị",
      "id": 8,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "10",
      "name": "Ông Trần Hoài Nam",
      "identity": "Phó Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng hợp Hội Đồng Quản Trị",
      "id": 9,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "11",
      "name": "Ông Bùi Văn Thảo",
      "identity": "Phó Tổng Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 10,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "12",
      "name": "Bà Phạm Thu Hiền",
      "identity": "Kế toán trưởng",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 11,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "13",
      "name": "Ông Hoàng Thế Vinh",
      "identity": "Trưởng Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 12,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "14",
      "name": "Ông Nguyễn Hoàng Quyền",
      "identity": "Phó Trưởng Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 13,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "15",
      "name": "Bà Nguyễn Thị Mai Phương",
      "identity": "Phó Trưởng Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng Giám Đốc",
      "id": 14,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "16",
      "name": "Ông Nguyễn Hải Nam",
      "identity": "Trưởng Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Kiểm toán nội bộ",
      "id": 15,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "17",
      "name": "Ông Phạm Phú Tiến",
      "identity": "Phó Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Kiểm toán nội bộ",
      "id": 16,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "18",
      "name": "Bà Trịnh Thị Quỳnh Hương",
      "identity": "Trưởng Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Quản trị rủi ro - Hội đồng quản trị",
      "id": 17,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "19",
      "name": "Bà Phạm Thị Nương",
      "identity": "Phó Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Quản trị rủi ro - Hội đồng quản trị",
      "id": 18,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "20",
      "name": "Bà Nguyễn Thị Hải Châu",
      "identity": "Chánh Văn phòng",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 19,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "21",
      "name": "Ông Cao Hữu Quý",
      "identity": "Phó Chánh Văn phòng",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 20,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "22",
      "name": "Ông Nguyễn Ngọc Toàn",
      "identity": "Phó Chánh Văn phòng",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 21,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "23",
      "name": "Bà Nguyễn Thị Thu Phương",
      "identity": "Trưởng phòng Hành chính tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 22,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "24",
      "name": "Ông Phạm Thái Việt",
      "identity": "Trưởng phòng Quản lý Đầu tư Xây dựng",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 23,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "25",
      "name": "Ông Nguyễn Minh Đức",
      "identity": "Phó Trưởng phòng Quản lý Đầu tư Xây dựng",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 24,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "26",
      "name": "Ông Bùi Phi Long",
      "identity": "Phó Trưởng phòng pháp chế",
      "x": 0,
      "y": 5,
      "department": "Văn phòng",
      "id": 25,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "27",
      "name": "Ông Bùi Quang Ngọc",
      "identity": "Giám đốc Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Nhân sự",
      "id": 26,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "28",
      "name": "Ông Nhữ Quang Phú",
      "identity": "Phó Giám đốc Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Nhân sự",
      "id": 27,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "29",
      "name": "Ông Nguyễn Hải Triều",
      "identity": "Phó Giám đốc Ban",
      "x": 0,
      "y": 5,
      "department": "Ban Nhân sự",
      "id": 28,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "30",
      "name": "Bà Trần Bích Ngọc",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 29,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "31",
      "name": "Ông Nguyễn Mạnh Thắng",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 30,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "32",
      "name": "Bà Đặng Thị Hoa Mai",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 31,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "33",
      "name": "Ông Bùi Quang Vinh",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 32,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "34",
      "name": "Ông Nguyễn Viết Sơn",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 33,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "35",
      "name": "Ông Lê Nhật Tiến",
      "identity": "Phó phụ trách phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 34,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "36",
      "name": "Ông Phạm Tuấn Tú",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 35,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "37",
      "name": "Ông Phan Viết Khôi",
      "identity": "Phó Trưởng Phòng Quản lý nghiệp vụ",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 36,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "38",
      "name": "Bà Nguyễn Thị Uyên",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 37,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "39",
      "name": "Ông Nguyễn Vũ Hội",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": " Ban Tài sản - Hỗn hợp",
      "id": 38,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "40",
      "name": "Ông Nguyễn Trung Hiếu",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Quản lý đại lý",
      "id": 39,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "41",
      "name": "Ông Tống Xuân Giang",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Xe cơ giới",
      "id": 40,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "42",
      "name": "Ông Trần Anh Tuấn",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bản Bảo hiểm kỹ thuật",
      "id": 41,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "43",
      "name": "Bà Trần Thị Mai Hồng",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bản Bảo hiểm kỹ thuật",
      "id": 42,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "44",
      "name": "Ông Nguyễn Đức Cường",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Công nghệ Thông tin",
      "id": 43,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "45",
      "name": "Ông Nguyễn Bình Dương",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 44,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "46",
      "name": "Bà Trần Thị Kim Hoàn",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 45,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "47",
      "name": "Ông Nguyễn Minh Nam",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 46,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "48",
      "name": "Bà Trần Thị Thu Ngân",
      "identity": "Phó Trưởng Phòng Quản lý nghiệp vụ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 47,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "49",
      "name": "Bà Nguyễn Thị Thùy Nhung",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 48,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "50",
      "name": "Ông Trần Hữu Nam",
      "identity": "Trưởng Phòng Quản lý nghiệp vụ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 49,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "51",
      "name": "Ông Nguyễn Viết Hòa",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Sức khỏe",
      "id": 50,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "52",
      "name": "Bà Hồ Thị Hồng Nhung",
      "identity": "Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Khách hàng Doanh nghiệp",
      "id": 51,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "53",
      "name": "Ông Lê Duy Hải",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Khách hàng Doanh nghiệp",
      "id": 52,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "54",
      "name": "Ông Đặng Quang Dũng",
      "identity": "Phó giám đốc phụ trách ",
      "x": 0,
      "y": 5,
      "department": "Ban Giám định bồi thường Xe cơ giới",
      "id": 53,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "55",
      "name": "Ông Nguyễn Hoàng Thăng Long",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Giám định bồi thường Xe cơ giới",
      "id": 54,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "56",
      "name": "Ông Đinh Quốc Thịnh",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Giám định bồi thường Xe cơ giới",
      "id": 55,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "57",
      "name": "Bà Hoàng Thị Yến Oanh",
      "identity": "Phó giám đốc phụ trách ",
      "x": 0,
      "y": 5,
      "department": "Ban Nghiên cứu thị trường và Quản trị rủi ro",
      "id": 56,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "58",
      "name": "Bà Nguyễn Thị Ngọc Bích",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tổng hợp Hội Đồng Quản Trị",
      "id": 57,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "59",
      "name": "Ông Phạm Thế Dân",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Kiểm Soát Nội Bộ",
      "id": 58,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "60",
      "name": "Ông Lương Minh Việt",
      "identity": "Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Đầu tư Tài chính",
      "id": 59,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "61",
      "name": "Bà Nguyễn Thúy Vân",
      "identity": "Phó giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Đầu tư Tài chính",
      "id": 60,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "62",
      "name": "Bà Ngô Khánh Linh",
      "identity": "Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Môi giới",
      "id": 61,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "63",
      "name": "Bà Đỗ Thị Mai",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Môi giới",
      "id": 62,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "64",
      "name": "Ông Hoàng Thanh Tùng",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Hàng hải",
      "id": 63,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "65",
      "name": "Ông Phan Kỳ Lân",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Hàng hải",
      "id": 64,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "66",
      "name": "Bà Lê Thị Thơm",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Hàng hải",
      "id": 65,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "67",
      "name": "Ông Nguyễn Học Huy",
      "identity": "Phó Trưởng phòng Giám định bồi thường",
      "x": 0,
      "y": 5,
      "department": "Ban Bảo hiểm Hàng hải",
      "id": 66,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "68",
      "name": "Bà Đặng Thị Ngọc Oanh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Tái bảo hiểm",
      "id": 67,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "69",
      "name": "Bà Trần Thanh Hiền",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Ban Tái bảo hiểm",
      "id": 68,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "70",
      "name": "Bà Nguyễn Thị Quỳnh Chi",
      "identity": "Phó phụ trách Phòng nhận Tái bảo hiểm",
      "x": 0,
      "y": 5,
      "department": "Ban Tái bảo hiểm",
      "id": 69,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "71",
      "name": "Ông Lê Quang Trung",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Truyền thông và Dịch vụ khách hàng",
      "id": 70,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "72",
      "name": "Bà Nguyễn Thu Hiền",
      "identity": "Trưởng phòng truyền thông",
      "x": 0,
      "y": 5,
      "department": "Ban Truyền thông và Dịch vụ khách hàng",
      "id": 71,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "73",
      "name": "Ông Ngô Đức Hưng",
      "identity": "Phó Trưởng phòng truyền thông",
      "x": 0,
      "y": 5,
      "department": "Ban Truyền thông và Dịch vụ khách hàng",
      "id": 72,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "74",
      "name": "Ông Đặng Đình Tuyên",
      "identity": "Phó Trưởng phòng Dịch vụ Khách hàng",
      "x": 0,
      "y": 5,
      "department": "Ban Truyền thông và Dịch vụ khách hàng",
      "id": 73,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "75",
      "name": "Bà Nguyễn Thị Quỳnh Trang",
      "identity": "Trưởng phòng Kế toán Văn Phòng",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 74,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "76",
      "name": "Bà Lê Ngọc Linh",
      "identity": "Phó Trưởng phòng Kế toán Văn Phòng",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 75,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "77",
      "name": "Ông Chu Công Nguyên",
      "identity": "Trưởng Phòng Kế toán Tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 76,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "78",
      "name": "Ông Phan Anh Minh",
      "identity": "Phó Trưởng Phòng Kế toán Tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 77,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "79",
      "name": "Bà Tạ Huyền Trang",
      "identity": "Phó Trưởng Phòng Kế toán Tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Ban Tài chính - Kế toán",
      "id": 78,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "80",
      "name": "Ông Đỗ Phúc Hiệp",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Phát triển giải pháp đa kênh",
      "id": 79,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "81",
      "name": "Bà Trịnh Thị Trà Giang",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Phát triển giải pháp đa kênh",
      "id": 80,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "82",
      "name": "Ông Nguyễn Anh Thái",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Ban Phát triển giải pháp đa kênh",
      "id": 81,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "83",
      "name": "Ông Nguyễn Duy Luân",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Cần Thơ",
      "id": 82,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "84",
      "name": "Ông Lê Thanh Tùng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Trà Vinh",
      "id": 83,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "85",
      "name": "Bà Nguyễn Thị Tuyết Vy",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đaklak",
      "id": 84,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "86",
      "name": "Ông Bùi Phụ Đức",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Quảng Ngãi",
      "id": 85,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "87",
      "name": "Ông Nguyễn Việt Năng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Tây Ninh",
      "id": 86,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "88",
      "name": "Ông Nguyễn Mạnh Hải",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bình Phước",
      "id": 87,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "89",
      "name": "Ông Hoàng Thế Hiền",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Vũng Tàu",
      "id": 88,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "90",
      "name": "Ông Nguyễn Thế Dũng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bình Dương",
      "id": 89,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "91",
      "name": "Ông Hà Thanh Nam",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Gia Định",
      "id": 90,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "92",
      "name": "Ông Nguyễn Văn Tâm",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bình Thuận",
      "id": 91,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "93",
      "name": "Ông Nguyễn Minh Giang",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Tiền Giang",
      "id": 92,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "94",
      "name": "Ông Nguyễn Khanh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Quảng Nam",
      "id": 93,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "95",
      "name": "Ông Nguyễn Trung Kiên",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "An Giang",
      "id": 94,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "96",
      "name": "Ông Huỳnh Văn Bảy",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Long An",
      "id": 95,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "97",
      "name": "Ông Nguyễn Văn Lê",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Nghệ An",
      "id": 96,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "98",
      "name": "Ông Nguyễn Văn Thịnh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thái bình",
      "id": 97,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "99",
      "name": "Ông Nguyễn Tiến Hải",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Lào Cai",
      "id": 98,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "100",
      "name": "Ông Nguyễn Huy Vinh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Giang",
      "id": 99,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "101",
      "name": "Bà Vũ Sơn Tùng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Yên Bái",
      "id": 100,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "102",
      "name": "Ông Lê Đình Dương",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thủ Đức",
      "id": 101,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "103",
      "name": "Ông Lê Thanh Hoàn",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Tĩnh",
      "id": 102,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "104",
      "name": "Ông Hoàng Tùng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bắc Ninh",
      "id": 103,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "105",
      "name": "Ông Đặng Quốc Bình",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Lạng Sơn",
      "id": 104,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "106",
      "name": "Ông Trương Đỗ Huy Phong",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đà Nẵng",
      "id": 105,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "107",
      "name": "Ông Ngô Thanh Liêm",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Sóc Trăng",
      "id": 106,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "108",
      "name": "Ông Nguyễn Văn Tèo",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Cà Mau",
      "id": 107,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "109",
      "name": "Ông Nguyễn Văn Thắng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bắc Giang",
      "id": 108,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "110",
      "name": "Ông Ngô Duy Minh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Phú Thọ",
      "id": 109,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "111",
      "name": "Ông Nguyễn Cao Minh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hải Phòng",
      "id": 110,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "112",
      "name": "Ông Trần Ngọc Thiện",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bạc Liêu",
      "id": 111,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "113",
      "name": "Ông Nguyễn Trọng Nhân",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thanh Hóa",
      "id": 112,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "114",
      "name": "Ông Trần Tuấn Hữu",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thái nguyên",
      "id": 113,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "115",
      "name": "Ông Phan Hồng Linh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Vĩnh Phúc",
      "id": 114,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "116",
      "name": "Ông Nguyễn Hướng Nam",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bình Định",
      "id": 115,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "117",
      "name": "Ông Nguyễn Thanh Sơn",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hòa Bình",
      "id": 116,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "118",
      "name": "Ông Bá Xuân Chiến",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đông Sài Gòn",
      "id": 117,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "119",
      "name": "Bà Trương Quang Khánh Thi",
      "identity": "Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Khánh Hòa",
      "id": 118,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "120",
      "name": "Ông Ngô Quốc Phòng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Nam Định",
      "id": 119,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "121",
      "name": "Ông Trần Nam Phong",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bến Thành",
      "id": 120,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "122",
      "name": "Ông Phạm Đức Hạnh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Tân Bình Dương",
      "id": 121,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "123",
      "name": "Ông Nguyễn Xuân Long",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Gia Lai",
      "id": 122,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "124",
      "name": "Ông Nguyễn Quang Huy",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Lâm Đồng",
      "id": 123,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "125",
      "name": "Ông Nguyễn Văn Duân",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hải Dương",
      "id": 124,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "126",
      "name": "Ông Phạm Xuân Trường",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Quảng Ninh",
      "id": 125,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "127",
      "name": "Ông Lê Huy Hưng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Sài Gòn",
      "id": 126,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "128",
      "name": "Ông Nguyễn Văn Tiến",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Bạch Đằng",
      "id": 127,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "129",
      "name": "Bà Võ Thị Hoa",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Huế",
      "id": 128,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "130",
      "name": "Ông Lê Văn Khải",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hưng Yên",
      "id": 129,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "131",
      "name": "Ông Nguyễn Quang Trung",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Quảng Bình",
      "id": 130,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "132",
      "name": "Ông Lê Quốc Hiệp",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Kiên Giang",
      "id": 131,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "133",
      "name": "Ông Nguyễn Văn Trường",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Nam",
      "id": 132,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "134",
      "name": "Ông Trần Thanh Thống",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đồng Tháp",
      "id": 133,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "135",
      "name": "Ông Hoàng Xuân Thắng",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Sơn La",
      "id": 134,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "136",
      "name": "Ông Thái Khắc Nhất",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đồng Nai",
      "id": 135,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "137",
      "name": "Ông Trần Anh Tuấn",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Nội",
      "id": 136,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "138",
      "name": "Ông Tăng Hoàng Việt",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Nội",
      "id": 137,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "139",
      "name": "Ông Nguyễn Hải Linh",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Nội",
      "id": 138,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "140",
      "name": "Bà Đào Thị Xuân Thu",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Thành",
      "id": 139,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "141",
      "name": "Ông Lê Quang Huy",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Thành",
      "id": 140,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "142",
      "name": "Ông Bùi Bá Thắng",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hà Thành",
      "id": 141,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "143",
      "name": "Ông Vũ Hữu Ngọc",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thủ Đô",
      "id": 142,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "144",
      "name": "Ông Đặng Văn Tuấn",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thủ Đô",
      "id": 143,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "145",
      "name": "Ông Quan Nguyễn Bảo Lâm",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Thủ Đô",
      "id": 144,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "146",
      "name": "Ông Trần Huy Thịnh",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đông Đô",
      "id": 145,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "147",
      "name": "Ông Dương Quốc Sử",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đông Đô",
      "id": 146,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "148",
      "name": "Ông Nguyễn Sỹ Bình",
      "identity": "Phó giám đốc",
      "x": 0,
      "y": 5,
      "department": "Đông Đô",
      "id": 147,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "149",
      "name": "Ông Lưu Thế Phương",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Tràng An",
      "id": 148,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "150",
      "name": "Ông Mã Duy Long",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Tràng An",
      "id": 149,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "151",
      "name": "Ông Nguyễn Hữu Cường",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Tràng An",
      "id": 150,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "152",
      "name": "Ông Bùi Tiến Long",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thăng Long",
      "id": 151,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "153",
      "name": "Ông Phạm Đình Tuấn",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Thăng Long",
      "id": 152,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "154",
      "name": "Ông Nguyễn Đức Tiến",
      "identity": "Phó Giám đốc ",
      "x": 0,
      "y": 5,
      "department": "Thăng Long",
      "id": 153,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "155",
      "name": "Bà Lê Thị Hồng Gấm",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Cần Thơ",
      "id": 154,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "156",
      "name": "Ông Lê Thanh Nhã",
      "identity": "Ủy viên Ban chấp hành Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Trà Vinh",
      "id": 155,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "157",
      "name": "Ông Nguyễn Thành Thái",
      "identity": "Phòng Kinh doanh, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đaklak",
      "id": 156,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "158",
      "name": "Ông Huỳnh Tuấn Huệ",
      "identity": "Trưởng Phòng KV3",
      "x": 0,
      "y": 5,
      "department": "Quảng Ngãi",
      "id": 157,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "159",
      "name": "Ông Nguyễn Công Khanh",
      "identity": "Trưởng Phòng NV1, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Tây Ninh",
      "id": 158,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "160",
      "name": "Bà Nguyễn Thị Mai ",
      "identity": "Trưởng Phòng KV1",
      "x": 0,
      "y": 5,
      "department": "Bình Phước",
      "id": 159,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "161",
      "name": "Bà Võ Thị Giang",
      "identity": "Trưởng Phòng Kế toán Tổng hợp, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Vũng Tàu",
      "id": 160,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "162",
      "name": "Ông Đặng Minh Huy",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Bình Dương",
      "id": 161,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "163",
      "name": "Ông Nguyễn Hữu Phước",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Gia Định",
      "id": 162,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "164",
      "name": "Ông Huỳnh Ngọc Thuận",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Bình Thuận",
      "id": 163,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "165",
      "name": "Bà Lê Thị Cẩm Nhân",
      "identity": "Phó Trưởng phòng Kế toán, Đại diện Người Lao Động",
      "x": 0,
      "y": 5,
      "department": "Tiền Giang",
      "id": 164,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "166",
      "name": "Ông Võ Minh Thiện",
      "identity": "Ủy viên Ban Chấp Hành Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Quảng Nam",
      "id": 165,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "167",
      "name": "Bà Trương Thị Lệ Phương",
      "identity": "Phó Trưởng Phòng Kế toán Tổng hợp, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "An Giang",
      "id": 166,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "168",
      "name": "Bà Nguyễn Thị Phương Thùy",
      "identity": "Trưởng Phòng Kế toán Tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Long An",
      "id": 167,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "169",
      "name": "Ông Nguyễn Xuân Thành ",
      "identity": "Trưởng Phòng nghiệp vụ II",
      "x": 0,
      "y": 5,
      "department": "Nghệ An",
      "id": 168,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "170",
      "name": "Ông Đỗ Trung Kiên",
      "identity": "Ban Chấp Hành Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Thái Bình",
      "id": 169,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "171",
      "name": "Ông Nguyễn Việt Cường",
      "identity": "Trưởng Phòng",
      "x": 0,
      "y": 5,
      "department": "Lào Cai",
      "id": 170,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "172",
      "name": "Bà Hà Nhật Lệ",
      "identity": "Trưởng Phòng Kế toán, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hà Giang",
      "id": 171,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "173",
      "name": "Bà Phạm Thị Hồng Thanh",
      "identity": "Trưởng Phòng Kế toán , Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Yên Bái",
      "id": 172,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "174",
      "name": "Ông Bùi Xuân Hà",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Thủ Đức",
      "id": 173,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "175",
      "name": "Ông Nguyễn Mạnh Cường",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hà Tĩnh",
      "id": 174,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "176",
      "name": "Bà Trịnh Thị Nhung",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Bắc Ninh",
      "id": 175,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "177",
      "name": "Bà Vương Tuyết Thanh",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Lạng Sơn",
      "id": 176,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "178",
      "name": "Bà Hồ Tường Vân",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đà Nẵng",
      "id": 177,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "179",
      "name": "Ông Bùi Văn Hiếu",
      "identity": "Trưởng Phòng Kế toán, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Sóc Trăng",
      "id": 178,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "180",
      "name": "Bà Ngô Kim Hồ",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Cà Mau",
      "id": 179,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "181",
      "name": "Bà Lê Thu Phương",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Bắc Giang",
      "id": 180,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "182",
      "name": "Ông Nguyễn Tuấn Đức",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Phú Thọ",
      "id": 181,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "183",
      "name": "Ông Nguyễn Việt Anh",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hải Phòng",
      "id": 182,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "184",
      "name": "Ông Quách Văn Nhân",
      "identity": "Trưởng Phòng Kế toán Tổng hợp, Đại diện Người Lao Động",
      "x": 0,
      "y": 5,
      "department": "Bạc Liêu",
      "id": 183,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "185",
      "name": "Ông Đào Minh Phương",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Thanh Hóa",
      "id": 184,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "186",
      "name": "Bà Phạm Thị Bích Hạnh",
      "identity": "Chủ tịch Công đoàn, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Thái nguyên",
      "id": 185,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "187",
      "name": "Ông Lê Anh Tuấn",
      "identity": "Phòng Sức khỏe, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Vĩnh Phúc",
      "id": 186,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "188",
      "name": "Bà Nguyễn Thị Mỹ Dung",
      "identity": "Chuyên viên",
      "x": 0,
      "y": 5,
      "department": "Bình Định",
      "id": 187,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "189",
      "name": "Ông Nguyễn Tiến Cường",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hòa Bình",
      "id": 188,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "190",
      "name": "Ông Bùi Hoàng Thiện",
      "identity": "Ủy viên Ban Chấp Hành Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đông Sài Gòn",
      "id": 189,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "191",
      "name": "Ông Trương Quang Tuấn Vũ ",
      "identity": "Trưởng Phòng",
      "x": 0,
      "y": 5,
      "department": "Khánh Hòa",
      "id": 190,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "192",
      "name": "Ông Trần Văn Diễn",
      "identity": "Chuyên viên Phòng Kinh doanh",
      "x": 0,
      "y": 5,
      "department": "Nam Định",
      "id": 191,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "193",
      "name": "Ông Nguyễn Đình Thanh",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Bến Thành",
      "id": 192,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "194",
      "name": "Ông Lê Hữu Mạnh",
      "identity": "Trưởng Phòng Kinh Doanh Bảo Hiểm số 01",
      "x": 0,
      "y": 5,
      "department": "Tân Bình Dương",
      "id": 193,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "195",
      "name": "Ông Tống Kỷ",
      "identity": "Trưởng Phòng Kế toán Tổng hợp",
      "x": 0,
      "y": 5,
      "department": "Gia Lai",
      "id": 194,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "196",
      "name": "Bà Nguyễn Thị Cảnh",
      "identity": "Chủ tịch Công đoàn, Ủy viên Ban chấp hành Công đoàn Tổng công ty",
      "x": 0,
      "y": 5,
      "department": "Lâm Đồng",
      "id": 195,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "197",
      "name": "Ông Nguyễn Đình Chuyên",
      "identity": "Phó phòng xe cơ giới, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hải Dương",
      "id": 196,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "198",
      "name": "Ông Đỗ Quang Vinh",
      "identity": "Phó Giám đốc , Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Quảng Ninh",
      "id": 197,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "199",
      "name": "Ông Trần Văn Trung",
      "identity": "Phó Giám đốc, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Sài Gòn",
      "id": 198,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "200",
      "name": "Ông Chử Bá Tùng",
      "identity": "Trưở̉ng phòng Tài sản và Kỹ thuật sức khỏe",
      "x": 0,
      "y": 5,
      "department": "Bạch Đằng",
      "id": 199,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "201",
      "name": "Bà Hoàng Thị Kim Thương",
      "identity": "Phó phòng Kinh doanh 3, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Huế",
      "id": 200,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "202",
      "name": "Ông Đinh Văn Thành",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Hưng Yên",
      "id": 201,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "203",
      "name": "Ông Đoàn Ngọc Giang",
      "identity": "Trưởng Phòng Kế toán tổng hợp, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Quảng Bình",
      "id": 202,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "204",
      "name": "Bà Đinh Ngọc Duyên",
      "identity": "Phó phòng Kế toán",
      "x": 0,
      "y": 5,
      "department": "Kiên Giang",
      "id": 203,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "205",
      "name": "Ông Trần Thanh Xuân",
      "identity": "Phòng Kinh doanh, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hà Nam",
      "id": 204,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "206",
      "name": "Bà Cao Thị Ngân Hà",
      "identity": "Chủ tịch Công đoàn, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đồng Tháp",
      "id": 205,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "207",
      "name": "Ông Đoàn Cảnh Sơn",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Sơn La",
      "id": 206,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "208",
      "name": "Bà Lê Thị Hiền Lương",
      "identity": "Trưởng Phòng Kế toán Tổng hợp, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Quảng Trị",
      "id": 207,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "209",
      "name": "Bà Phạm Thị Phương Thảo",
      "identity": "Chủ tịch Công đoàn, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đồng Nai",
      "id": 208,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "210",
      "name": "Ông Trần Xuân Mai",
      "identity": "Chủ tịch Công đoàn, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Tuyên Quang",
      "id": 209,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "211",
      "name": "Bà Võ Thị Thùy Trang",
      "identity": "Trưởng Phòng Kế toán, Đại diện Người Lao Động",
      "x": 0,
      "y": 5,
      "department": "Phú Yên",
      "id": 210,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "212",
      "name": "Ông Nguyễn Tiến Sơn",
      "identity": "Trưởng Phòng Xe cơ giới, Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hà Nội",
      "id": 211,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "213",
      "name": "Bà Lương Thị Thu Trang",
      "identity": "Phó phòng Bảo hiểm Sức khỏe, Ủy viên Ban Chấp Hành Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Hà Thành",
      "id": 212,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "214",
      "name": "Bà Lê Huyền Trang",
      "identity": "Chủ tịch Công đoàn",
      "x": 0,
      "y": 5,
      "department": "Đông Đô",
      "id": 213,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "215",
      "name": "Bà Trần Thị Cẩm Vân",
      "identity": "Trưởng phòng Bảo hiểm Sức khỏe, Đại diện Người Lao Động",
      "x": 0,
      "y": 5,
      "department": "Tràng An",
      "id": 214,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "216",
      "name": "Ông Nguyễn Đồng",
      "identity": "Chủ tịch",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Khu vực 1",
      "id": 215,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "217",
      "name": "Ông Hoàng Văn Bình",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Khu vực 2",
      "id": 216,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "218",
      "name": "Ông Vũ Tuyên Huấn",
      "identity": "Giám đốc Chi nhánh Xăng dầu Hà Nội",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Khu vực 3",
      "id": 217,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "219",
      "name": "Ông Lê Đức Hưởng",
      "identity": "Giám đốc Tổng kho Đức Giang",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Khu vực 4",
      "id": 218,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "220",
      "name": "Ông Bùi Văn Thành",
      "identity": "Chủ tịch Hội đồng quản trị",
      "x": 0,
      "y": 5,
      "department": "Công ty CP Thương mại và Vận tải Petrolimex Hà Nội",
      "id": 219,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "221",
      "name": "Ông Phạm Quốc Hùng",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty CP Thương mại và Vận tải Petrolimex Hà Nội",
      "id": 220,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "222",
      "name": "Ông Vũ Quang Tuấn",
      "identity": "Chủ tịch kiêm Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Hà Sơn Bình",
      "id": 221,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "223",
      "name": "Ông Lê Tự Cường",
      "identity": "Chủ tịch",
      "x": 0,
      "y": 5,
      "department": "Công ty PTS Hà Tây",
      "id": 222,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "224",
      "name": "Ông Nguyễn Tử Bình",
      "identity": "Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty PTS Hà Tây",
      "id": 223,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "225",
      "name": "Ông Nguyễn Đăng Quốc",
      "identity": "Phó Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Tuyên Quang",
      "id": 224,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "226",
      "name": "Ông Đỗ Lâm Bằng",
      "identity": "Trưởng phòng Kinh doanh",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Tuyên Quang",
      "id": 225,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "227",
      "name": "Ông Ngô Quang Vinh",
      "identity": "Chủ tịch kiêm Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Lai Châu",
      "id": 226,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "228",
      "name": "Ông Nguyễn Khoa Phong Điền",
      "identity": "Chủ tịch kiêm Giám đốc",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Thừa Thiên Huế",
      "id": 227,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "229",
      "name": "Ông Nguyễn Hữu Thanh",
      "identity": "Kế toán trưởng",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Thừa Thiên Huế",
      "id": 228,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    },
    {
      "uid": "230",
      "name": "Bà Phạm Thị Hồng Yêm",
      "identity": "Giám đốc Chi nhánh Bình Phước",
      "x": 0,
      "y": 5,
      "department": "Công ty Xăng dầu Sông Bé",
      "id": 229,
      "createTime": "2025-01-11 12:13:40",
      "updateTime": "2025-01-11 12:13:40",
      "prizeName": [],
      "prizeTime": [],
      "prizeId": [],
      "isWin": false
    }
  ]

export const defaultMusicList = [
  {
    id: 'Geoff Knorr - China (The Industrial Era).ogg' + new Date().getTime().toString(),
    name: 'Geoff Knorr - China (The Industrial Era).ogg',
    url: 'https://1kw20.fun/resource/audio/Geoff Knorr - China (The Industrial Era).ogg'
  },
  {
    id: 'xsmb' + new Date().getTime().toString(),
    name: 'XSMB music',
    url: 'xsmb.mp3'
  },

]

export const defaultPrizeList = <IPrizeConfig[]>[
  {
    id: '000',
    name: 'Giải khuyến khích 1',
    sort: 0,
    isAll: false,
    count: 15,
    isUsedCount: 0,
    picture: {
      id: '2',
      name: 'image_3',
      url: 'https://1kw20.fun/resource/image/image3.png'
    },
    separateCount: {
      enable: true,
      countList: []
    },
    desc: 'Giải khuyến khích 1',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '001',
    name: 'Giải khuyến khích 2',
    sort: 1,
    isAll: false,
    count: 15,
    isUsedCount: 0,
    picture: {
      id: '2',
      name: 'image_3',
      url: 'https://1kw20.fun/resource/image/image3.png'
    },
    separateCount: {
      enable: true,
      countList: []
    },
    desc: 'Giải khuyến khích 2',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '002',
    name: 'Giải ba',
    sort: 2,
    isAll: false,
    count: 15,
    isUsedCount: 0,
    picture: {
      id: '1',
      name: 'image_2',
      url: 'https://1kw20.fun/resource/image/image2.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải ba',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '003',
    name: 'Giải nhì',
    sort: 1,
    isAll: false,
    count: 5,
    isUsedCount: 0,
    picture: {
      id: '0',
      name: 'image_1',
      url: 'https://1kw20.fun/resource/image/image1.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải nhì',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '004',
    name: 'Giải nhất',
    sort: 4,
    isAll: false,
    count: 3,
    isUsedCount: 0,
    picture: {
      id: '3',
      name: 'image_3',
      url: 'https://1kw20.fun/resource/image/image3.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải nhất',
    isShow: true,
    isUsed: false,
    frequency: 1,
  },
  {
    id: '005',
    name: 'Giải đặc biệt',
    sort: 5,
    isAll: false,
    count: 1,
    isUsedCount: 0,
    picture: {
      id: '4',
      name: 'image_4',
      url: 'https://1kw20.fun/resource/image/image4.png'
    },
    separateCount: {
      enable: false,
      countList: []
    },
    desc: 'Giải đặc biệt',
    isShow: true,
    isUsed: false,
    frequency: 1,
  }
]
export const defaultCurrentPrize = <IPrizeConfig>{
  id: '001',
  name: 'Giải ba',
  sort: 1,
  isAll: false,
  count: 12,
  isUsedCount: 0,
  picture: {
    id: '2',
    name: 'image_3',
    url: 'https://1kw20.fun/resource/image/image3.png'
  },
  separateCount: {
    enable: true,
    countList: []
  },
  desc: 'Giải ba',
  isShow: true,
  isUsed: false,
  frequency: 1,
}
export const defaultTemporaryPrize = <IPrizeConfig>{
  id: '',
  name: '',
  sort: 0,
  isAll: false,
  count: 1,
  isUsedCount: 0,
  picture: {
    id: '-1',
    name: '',
    url: ''
  },
  separateCount: {
    enable: true,
    countList: []
  },
  desc: '',
  isShow: false,
  isUsed: false,
  frequency: 1,
}

export const defaultImageList = [
  {
    id: '0',
    name: 'background',
    url: 'bg-1.jpg'
  },
  // {
  //     id: '1',
  //     name: 'image_2',
  //     url: 'https://1kw20.fun/resource/image/image2.png'
  // },
  // {
  //     id: '2',
  //     name: 'image_3',
  //     url: 'https://1kw20.fun/resource/image/image3.png'
  // },
  // {
  //     id: '3',
  //     name: 'image_4',
  //     url: 'https://1kw20.fun/resource/image/image4.png'
  // },
  // {
  //     id: '4',
  //     name: 'image_5',
  //     url: 'https://1kw20.fun/resource/image/image5.png'
  // }
]
export const defaultPatternList = [21, 38, 55, 54, 53, 70, 87, 88, 89, 23, 40, 57, 74, 91, 92, 93, 76, 59, 42, 25, 24, 27, 28, 29, 46, 63, 62, 61, 78, 95, 96, 97, 20, 19, 31, 48, 65, 66, 67, 84, 101, 100, 99, 32, 33]
